In [1]:
import pandas as pd
import geopandas as gpd

In [40]:
def activity_summary(activity_old_path, activity_old_lyr_name, activity_new_path, activity_new_lyr_name, output_csv_path, summary_cols):
    activity_old = gpd.read_file(activity_old_path,
                          driver='OpenFileGDB',
                          layer=activity_old_lyr_name)
    activity_new = gpd.read_file(activity_new_path,
                              driver='OpenFileGDB',
                              layer=activity_new_lyr_name)
    
    summary_old = activity_old.groupby(summary_cols).ACTIVITY_QUANTITY.sum().reset_index()
    summary_new = activity_new.groupby(summary_cols).ACTIVITY_QUANTITY.sum().reset_index()
    summary_df = summary_old.merge(summary_new, on=summary_cols, how='outer')
    summary_df = summary_df.rename({'ACTIVITY_QUANTITY_x': 'ACTIVITY_QUANTITY_old', 'ACTIVITY_QUANTITY_y': 'ACTIVITY_QUANTITY_new'}, axis=1)
    summary_df['ACTIVITY_QUANTITY_new'] = summary_df['ACTIVITY_QUANTITY_new'].fillna(0)
    summary_df['ACTIVITY_QUANTITY_old'] = summary_df['ACTIVITY_QUANTITY_old'].fillna(0)
    summary_df['ACTIVITY_QUANTITY_diff'] = summary_df['ACTIVITY_QUANTITY_new'] - summary_df['ACTIVITY_QUANTITY_old']
    summary_df['ACTIVITY_QUANTITY_abs'] = summary_df['ACTIVITY_QUANTITY_diff'].abs()
    summary_df.sort_values(by='ACTIVITY_QUANTITY_abs', ascending=False, inplace=True)
    summary_df.to_csv(output_csv_path)
    return summary_df

In [41]:
summary_df = activity_summary('ITS_V2_0_Activity_webmap.gdb',
                              'ITS_V2_0_Activity',
                              'ITSV2.1_Activity_webmap.gdb',
                              'ITSV2_1_Activity_webmap',
                              'ITS_activity_v2.0_vs_v2.1_comparison.csv',
                              ['ADMINISTERING_ORG', 'ACTIVITY_DESCRIPTION', 'ACTIVITY_CAT', 'Year_txt'])

/usr/local/lib/python3.10/dist-packages/pyogrio/raw.py:198: RuntimeWarning: driver OpenFileGDB does not support open option DRIVER
  return ogr_read(
/usr/local/lib/python3.10/dist-packages/pyogrio/raw.py:198: RuntimeWarning: driver OpenFileGDB does not support open option DRIVER
  return ogr_read(

In [42]:
summary_df[summary_df['ACTIVITY_CAT'] == 'SANI_SALVG']

,ADMINISTERING_ORG,ACTIVITY_DESCRIPTION,ACTIVITY_CAT,Year_txt,ACTIVITY_QUANTITY_old,ACTIVITY_QUANTITY_new,ACTIVITY_QUANTITY_diff,ACTIVITY_QUANTITY_abs
801,USFS,SANI_HARVEST,SANI_SALVG,2022,0.0,436.4,436.4,436.4
800,USFS,SANI_HARVEST,SANI_SALVG,2021,0.0,292.3,292.3,292.3
804,USFS,SANI_HARVEST,SANI_SALVG,2025,0.0,258.0,258.0,258.0
802,USFS,SANI_HARVEST,SANI_SALVG,2023,0.0,121.6,121.6,121.6
803,USFS,SANI_HARVEST,SANI_SALVG,2024,0.0,94.1,94.1,94.1

In [43]:
summary_df[summary_df['ADMINISTERING_ORG'] == 'DOD']

,ADMINISTERING_ORG,ACTIVITY_DESCRIPTION,ACTIVITY_CAT,Year_txt,ACTIVITY_QUANTITY_old,ACTIVITY_QUANTITY_new,ACTIVITY_QUANTITY_diff,ACTIVITY_QUANTITY_abs
310,DOD,BROADCAST_BURN,PRESCRB_FIRE,2025,0.00,11122.06,1.112206e+04,1.112206e+04
309,DOD,BROADCAST_BURN,PRESCRB_FIRE,2024,2963.43,2963.43,-4.547474e-13,4.547474e-13
311,DOD,PILE_BURN,PRESCRB_FIRE,2021,9.50,9.50,0.000000e+00,0.000000e+00
313,DOD,PILE_BURN,PRESCRB_FIRE,2023,19.93,19.93,0.000000e+00,0.000000e+00
314,DOD,PILE_BURN,PRESCRB_FIRE,2024,3.90,3.90,0.000000e+00,0.000000e+00
312,DOD,PILE_BURN,PRESCRB_FIRE,2022,4.00,4.00,0.000000e+00,0.000000e+00
306,DOD,BROADCAST_BURN,PRESCRB_FIRE,2021,6171.50,6171.50,0.000000e+00,0.000000e+00
307,DOD,BROADCAST_BURN,PRESCRB_FIRE,2022,4663.00,4663.00,0.000000e+00,0.000000e+00
308,DOD,BROADCAST_BURN,PRESCRB_FIRE,2023,1863.30,1863.30,0.000000e+00,0.000000e+00

In [44]:
summary_df[summary_df['ADMINISTERING_ORG'] == 'DOC']

,ADMINISTERING_ORG,ACTIVITY_DESCRIPTION,ACTIVITY_CAT,Year_txt,ACTIVITY_QUANTITY_old,ACTIVITY_QUANTITY_new,ACTIVITY_QUANTITY_diff,ACTIVITY_QUANTITY_abs
302,DOC,PILE_BURN,PRESCRB_FIRE,2022,0.0,121.098,121.098,121.098
303,DOC,PRESCRB_HERBIVORY,GRAZING,2022,0.0,30.000,30.000,30.000
304,DOC,PRESCRB_HERBIVORY,GRAZING,2023,0.0,30.000,30.000,30.000
305,DOC,THIN_MECH,MECH_HFR,2021,0.0,1.445,1.445,1.445
301,DOC,PILE_BURN,PRESCRB_FIRE,2021,0.0,1.445,1.445,1.445
300,DOC,BROADCAST_BURN,PRESCRB_FIRE,2021,0.0,1.445,1.445,1.445